CREATE TABLE "rooms" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "room_uid" uuid NOT NULL UNIQUE,
                         "created_by" bigint NOT NULL,
                         "created_at" timestamptz NOT NULL,
                         "closed_at" timestamptz,
                         "close_reason" varchar(20)
);

ALTER TABLE "rooms" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "room_participations" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "room_uid" uuid NOT NULL,
                         "user_id" bigint NOT NULL,
                         "joined_at" timestamptz NOT NULL,
                         "left_at" timestamptz,
                         "leave_reason" varchar(20)
);

ALTER TABLE "room_participations" ADD FOREIGN KEY ("room_uid") REFERENCES "rooms" ("room_uid") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "room_participations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE INDEX ON "room_participations" ("user_id", "joined_at");
CREATE INDEX ON "room_participations" ("room_uid");
