-- 공지 팝업(BY-376)의 공지 원본. BY-833에서 인터뷰 모집 공지(ADR-0027)를 위해 대상·배지·버튼·on/off를 더했다.
-- 운영자가 직접 INSERT로 발행하고, 앱은 GET /api/notices/active(인증)로 노출 기간 안의 자기 대상 공지만 조회한다.
CREATE TABLE "notice" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(100) NOT NULL,
    "content" text NOT NULL,
    "image_url" varchar(500),
    -- ALL은 전원, 나머지는 서버가 판정한 인터뷰 대상 그룹에게만 내려간다
    "audience" varchar(30) NOT NULL DEFAULT 'ALL'
        CHECK ("audience" IN ('ALL', 'G1_NOT_STARTED', 'G2_LAPSED')),
    "badge_text" varchar(50),
    "button_text" varchar(30),
    "button_url" varchar(500),
    -- 기간을 건드리지 않고 끄고 켜는 스위치
    "enabled" boolean NOT NULL DEFAULT true,
    "starts_at" timestamptz NOT NULL,
    -- 운영자가 직접 INSERT하므로 기간 역전 오입력을 DB가 막는다
    "ends_at" timestamptz CHECK ("ends_at" IS NULL OR "starts_at" < "ends_at"),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    -- 버튼은 문구와 링크가 함께 있어야 누를 수 있다
    CHECK (("button_text" IS NULL) = ("button_url" IS NULL))
);
