-- U2 공지 팝업(BY-376)의 공지 원본. 운영자가 직접 INSERT로 발행하고,
-- 앱은 GET /api/notices/active로 노출 기간 안의 공지만 조회한다.
CREATE TABLE "notice" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(100) NOT NULL,
    "content" text NOT NULL,
    "image_url" varchar(500),
    "starts_at" timestamptz NOT NULL,
    -- 운영자가 직접 INSERT하므로 기간 역전 오입력을 DB가 막는다
    "ends_at" timestamptz CHECK ("ends_at" IS NULL OR "starts_at" < "ends_at"),
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now()
);
